export const PERMISSION_KEYS = [
  "consultancy.read",
  "consultancy.update",
  "consultancy.branding.update",
  // Legacy aliases kept for backward compatibility with existing data.
  "tenant.read",
  "tenant.update",
  "tenant.branding.update",
  "user.create",
  "user.read",
  "user.update",
  "user.suspend",
  "role.create",
  "role.read",
  "role.update",
  "role.delete",
  "role.assign",
  "permission.manage",
  "lead.create",
  "lead.read",
  "lead.update",
  "lead.delete",
  "lead.convert",
  "student.create",
  "student.read",
  "student.update",
  "student.delete",
  "case.create",
  "case.read",
  "case.update",
  "case.close",
  "doc.request.create",
  "doc.request.read",
  "doc.request.update",
  "doc.request.cancel",
  "doc.upload",
  "doc.read",
  "doc.verify",
  "doc.reject",
  "doc.version.read",
  "storage.sign.upload",
  "storage.sign.download",
  "audit.read",
  "report.read",
] as const;

export const DEFAULT_ROLE_PERMISSION_KEYS: Record<string, string[]> = {
  SUPER_ADMIN: [...PERMISSION_KEYS],
  STUDENT_PORTAL: [],
  COUNSELOR: [
    "lead.create",
    "lead.read",
    "lead.update",
    "lead.delete",
    "lead.convert",
    "student.create",
    "student.read",
    "student.update",
    "student.delete",
    "doc.request.create",
    "doc.request.read",
    "doc.request.update",
    "doc.request.cancel",
    "doc.read",
  ],
  DOCUMENTATION_OFFICER: [
    "doc.request.create",
    "doc.request.read",
    "doc.request.update",
    "doc.request.cancel",
    "doc.upload",
    "doc.read",
    "doc.verify",
    "doc.reject",
  ],
  VISA_OFFICER: [
    "student.read",
    "case.create",
    "case.read",
    "case.update",
    "case.close",
    "doc.read",
  ],
  ACCOUNTANT: ["report.read"],
  RECEPTIONIST: [
    "lead.create",
    "lead.read",
    "lead.update",
    "student.create",
    "student.read",
    "doc.request.read",
  ],
};

export const DEFAULT_ROLE_NAMES: Record<string, string> = {
  SUPER_ADMIN: "Super Admin",
  STUDENT_PORTAL: "Student Portal",
  COUNSELOR: "Counselor",
  DOCUMENTATION_OFFICER: "Documentation Officer",
  VISA_OFFICER: "Visa Officer",
  ACCOUNTANT: "Accountant",
  RECEPTIONIST: "Receptionist",
};
